version: '3.7'
services:
  data-generator:
    build: ./data-generator
    container_name: data-generator
    depends_on:
      redpanda: { condition: service_healthy }
  redpanda:
    image: docker.vectorized.io/vectorized/redpanda:v21.11.3
    container_name: redpanda
    command:
     - redpanda start
     - --overprovisioned
     - --smp 1
     - --memory 1G
     - --reserve-memory 0M
     - --node-id 0
     - --check=false
     - --kafka-addr 0.0.0.0:9092
     - --advertise-kafka-addr redpanda:9092
     - --pandaproxy-addr 0.0.0.0:8082
     - --advertise-pandaproxy-addr redpanda:8082
     - --set redpanda.enable_transactions=true
     - --set redpanda.enable_idempotence=true
     - --set redpanda.auto_create_topics_enabled=true
    ports:
      - "9092:9092"
      - "8081:8081"
      - "8082:8082"
    healthcheck: { test: curl -f localhost:9644/v1/status/ready, interval: 1s, start_period: 30s }
  materialized:
    image: materialize/materialized:v0.20.0
    container_name: materialized
    command: -w1
    ports:
      - "6875:6875"
  mzcli:
    image: materialize/cli
    container_name: mzcli
  dbt:
    build:
      context: ./dbt
      target: dbt-third-party
      args:
        - build_for=${ARCH}
    container_name: dbt
    ports:
      - "8000:8080"
    volumes:
      - ./dbt/profiles.yml:/root/.dbt/profiles.yml
      - ./dbt/:/usr/app/dbt
    stdin_open: true
    tty: true
    depends_on:
      - materialized
  metabase:
    image: ${MIMG}/metabase
    container_name: metabase
    depends_on:
      - materialized
    ports:
      - "3030:3000"
  debezium:
    image: debezium/connect
    depends_on:
      - redpanda
      - mysql
    ports:
      - "8083:8083"
    environment:
      BOOTSTRAP_SERVERS: "redpanda:9092"
      GROUP_ID: "1"
      CONFIG_STORAGE_TOPIC: "inventory.configs"
      OFFSET_STORAGE_TOPIC: "inventory.offset"
      STATUS_STORAGE_TOPIC: "inventory.status"
      KEY_CONVERTER: io.confluent.connect.avro.AvroConverter
      VALUE_CONVERTER: io.confluent.connect.avro.AvroConverter
      CONNECT_KEY_CONVERTER_SCHEMA_REGISTRY_URL: http://redpanda:8081
      CONNECT_VALUE_CONVERTER_SCHEMA_REGISTRY_URL: http://redpanda:8081
  mysql:
    image: debezium/example-mysql:1.6
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: debezium
      MYSQL_USER: mysqluser
      MYSQL_PASSWORD: mysqlpw
